#Create ID to identify levels
cls <- data.frame(id=1:4, category=c("Unused data", "Background", "Presence",
                                  "Presence & Background"))

explore_calibration_geo <- function(data, #Data (list) generated by prepare_data() function
                                    spat_variables, #Any spatial variable (Spatraster)
                                    plot = TRUE){ #Return plot?

  #Extract cell values
  bg <- data$data_xy[data$calibration_data$pr_bg == 0,]
  p <- data$data_xy[data$calibration_data$pr_bg == 1,]

  #Get cells
  bg_cells <- terra::extract(spat_variables, bg, cells = TRUE, ID = FALSE)$cell
  p_cells <- terra::extract(spat_variables, p, cells = TRUE, ID = FALSE)$cell
  p_bg_cells <- intersect(bg_cells, p_cells)

  #Fill rasters
  r <- (!is.na(spat_variables[[1]])) * 1
  terra::NAflag(r) <- 0 #Set NA
  r[bg_cells] <- 2
  r[p_cells] <- 3
  r[p_bg_cells] <- 4
  #Set levels
  levels(r) <- cls
  #Crop and trim final raster
  r <- terra::trim(terra::crop(r, spat_variables[[1]], mask = TRUE))

  if(plot){
  terra::plot(r)}
  return(r)
}

#
# # #Test function
# library(terra)
# data <- readRDS("../test_kuenm2/Myrcia.RDS")
# var <- terra::rast(system.file("extdata", "WorldClim_Variables.tiff",  # ??
#                                package = "kuenm2"))
# spat_variables<- var$bio_1
# edata <- explore_calibration_geo(data = data, spat_variables = var$bio_1, plot = TRUE)
# edata


