#' Transform variables using Principal Component analysis (PCA)
#'
#' @description
#' This function applies principal component analysis (PCA) to a set of
#' predictor variables. It transforms and project them into a new set of
#' uncorrelated, orthogonal components based on the PCA axes, which can be used
#' to simplify data structure and reduce correlations.
#'
#' @param spat_variables (SpatRaster) set of predictor variables that the
#'        function will summarize into a set of orthogonal, uncorrelated
#'        components based on PCA.
#' @param exclude_from_pca (character) variable names within spat_variables that
#'        should not be included in the PCA transformation. Instead, these
#'        variables will be added directly to the final set of output variables
#'        without being modified. The default is NULL, meaning all variables
#'        will be used unless specified otherwise.
#' @param project (logical) whether the function should project new data from
#'        different scenarios (e.g. future variables) onto the PCA coordinates
#'        generated by the initial analysis. If TRUE, the argument
#'        projection_data needs to be defined. Default is FALSE.
#' @param projection_data an object of class `prepared_proj` returned by the
#'        \code{\link{prepare_proj()}}() function. This file contains the paths
#'        to the rasters representing each scenario. Only applicable if
#'        `project = TRUE`. Default is NULL.
#' @param out_dir (character) a path to a root directory for saving the raster
#'        files of each projection.
#' @param overwrite (logical) whether to overwrite SpatRaster if they already
#'        exists when projecting. Only applicable if `write_files` is set to
#'        TRUE. Default is FALSE.
#' @param progress_bar (logical) whether to display a progress bar during
#'        processing projections. Only applicable if `project = TRUE`. Default
#'        is FALSE
#' @param center (logical) whether the variables should be zero-centered.
#'        Default is TRUE.
#' @param scale (logical) whether the variables should be scaled to have unit
#'        variance before the analysis takes place. Default is TRUE.
#' @param deviance_explained (numeric) the cumulative percentage of total
#'        variance that must be explained by the selected principal components.
#'        Default is 95.
#' @param min_explained (numeric) the minimum percentage of total variance that
#'        a principal component must explain to be retained. Default is 5.
#'
#' @return A list containing the following elements:
#' - env: A SpatRaster object that holds the orthogonal components derived from
#' the PCA axes of the predictor variables.
#' - pca: an object of class prcomp, containing the details of the PCA analysis.
#' See \code{\link{stats::prcomp()}}()
#' - deviance_explained_cum_sum: The cumulative percentage of total variance
#' explained by each of the selected principal components. This value indicates
#' how much of the data’s original variability is captured by the PCA
#' transformation.
#' - projection_directory: the root directory where projection files were saved,
#' applicable only if `project` was set to TRUE. This directory contains the
#' projected raster files for each scenario.
#'
#' @importFrom terra prcomp predict writeRaster rast
#' @importFrom utils txtProgressBar setTxtProgressBar
#' @export
#'
#' @usage perform_pca(spat_variables, exclude_from_pca = NULL, project = FALSE,
#'        projection_data = NULL, out_dir = NULL, overwrite = FALSE,
#'        progress_bar = FALSE, center = TRUE, scale = TRUE,
#'        deviance_explained = 95, min_explained = 5)
#'
#' @examples
#' #PCA only with current variables
#' #Import raster layers
#' var <- terra::rast(system.file("extdata", "Current_variables.tif",
#'                                package = "kuenm2"))
#'
#' #PCA
#' pca_var <- perform_pca(spat_variables = var, exclude_from_pca = "SoilType",
#'                        center = TRUE, scale = TRUE, deviance_explained = 95,
#'                        min_explained = 5)
#' plot(pca_var$env)
#'
#' #Project PCA for new scenarios (future)
#' # First, organize and prepare future variables
#' # Set the input directory containing the raw future climate variables
#' # For this example, the data is located in the "inst/extdata" folder.
#' in_dir <- "inst/extdata/"
#' # Create a "Future_raw" folder in a temporary directory and copy the raw variables there.
#' out_dir_future <- file.path(tempdir(), "Future_raw")
#' # Organize and rename the future climate data, structuring it by year and GCM.
#' # The 'SoilType' variable will be appended as a static variable in each scenario.
#' # The files will be renamed following the "bio_" format
#' organize_future_worldclim(input_dir = in_dir,
#'                           output_dir = out_dir_future,
#'                           name_format = "bio_", variables = NULL,
#'                           fixed_variables = var$SoilType, mask = NULL,
#'                           overwrite = TRUE)
#'
#' # Prepare projections
#' pr <- prepare_proj(variable_names = c("bio_1", "bio_7", "bio_12", "bio_15",
#'                                       "SoilType"),
#'                    present_dir = NULL,
#'                    past_dir = NULL,
#'                    past_period = NULL,
#'                    past_gcm = NULL,
#'                    future_dir = out_dir_future,
#'                    future_period = c("2041-2060", "2081-2100"),
#'                    future_pscen = c("ssp126", "ssp585"),
#'                    future_gcm = c("ACCESS-CM2", "MIROC6"),
#'                    write_file = FALSE,
#'                    filename = NULL,
#'                    raster_pattern = ".tif*")
#'
#' #Create folder to save projection results
#' out_dir <- file.path(tempdir(), "PCA_projections")
#' dir.create(out_dir, recursive = TRUE)
#'
#' #Perform and project PCA for new scenarios (future)
#' proj_pca <- perform_pca(spat_variables = var, exclude_from_pca = "SoilType",
#'                         project = TRUE, projection_data = pr, out_dir = out_dir,
#'                         overwrite = TRUE, progress_bar = FALSE,
#'                         center = TRUE, scale = TRUE,
#'                         deviance_explained = 95,
#'                         min_explained = 5)
#' proj_pca$projection_directory #Directory with projected PCA-variables
#'
perform_pca <- function(spat_variables, exclude_from_pca = NULL,
                       project = FALSE, projection_data = NULL, out_dir = NULL,
                       overwrite = FALSE, progress_bar = FALSE,
                       center = TRUE, scale = TRUE,
                       deviance_explained = 95, min_explained = 5) {

  #Check data
  if (!inherits(spat_variables, "SpatRaster")) {
    stop(paste0("Argument spat_variables must be a SpatRaster, not ",
                class(spat_variables)))
  }
  if (!is.null(exclude_from_pca) & !inherits(exclude_from_pca, "character")) {
    stop(paste0("Argument exclude_from_pca must be NULL or a character, not ",
                class(exclude_from_pca)))
  }
  if (!inherits(project, "logical")) {
    stop(paste0("Argument project must be logical, not ",
                class(project)))
  }
  if (project & is.null(projection_data)){
    stop("If project is set to TRUE, projection_data must be specified")
  }
  if (project & !is.null(projection_data) & !inherits(projection_data, "projection_data")) {
    stop(paste0("Argument projection_data must be a projection_data object, not ",
                class(projection_data)))
  }
  if (project & is.null(out_dir)){
    stop("If project is set to TRUE, out_dir must be specified")
  }
  if (project & !is.null(out_dir) & !inherits(out_dir, "character")) {
    stop(paste0("Argument out_dir must be a character, not ",
                class(out_dir)))
  }
  if (project & !inherits(overwrite, "logical")) {
    stop(paste0("Argument overwrite must be logical, not ",
                class(overwrite)))
  }
  if (project & !inherits(progress_bar, "logical")) {
    stop(paste0("Argument progress_bar must be logical, not ",
                class(progress_bar)))}
  if (!inherits(center, "logical")) {
    stop(paste0("Argument center must be logical, not ",
                class(center)))}
  if (!inherits(scale, "logical")) {
    stop(paste0("Argument scale must be logical, not ",
                class(scale)))}
  if (!is.numeric(deviance_explained)) {
    stop(paste0("Argument deviance_explained must be numeric, not ",
                class(deviance_explained)))
  }
  if (!is.numeric(min_explained)) {
    stop(paste0("Argument min_explained must be numeric, not ",
                class(min_explained)))
  }

  #Check if variables are present in projection data
  if(project){
  var_out <- setdiff(names(spat_variables), pr$variables)
  if(length(var_out) > 0){
    stop("One or more variables from spat_variables are missing in projection_data.
Ensure that all variables specified in spat_variables are available in projection_data when project = TRUE")
  }
  }

  #End of check data

  if (!is.null(exclude_from_pca)) {
    var_to_pca <-  setdiff(names(spat_variables), exclude_from_pca)
  } else {
    var_to_pca <- names(spat_variables)
  }

  pca <- terra::prcomp(spat_variables[[var_to_pca]], center = center, scale = scale)
  pca$x <- NULL
  pca$vars_in <- var_to_pca
  pca$vars_out <- exclude_from_pca

  d_exp <- cumsum(pca$sdev^2/sum(pca$sdev^2)) * 100
  d_exp <- d_exp[(pca$sdev^2/sum(pca$sdev^2) * 100) > min_explained]

  ind_exp <- if (max(d_exp) > deviance_explained) min(which(d_exp >= deviance_explained)) else length(d_exp)

  env <- terra::predict(spat_variables[[var_to_pca]], pca, index = 1:ind_exp)

  if (!is.null(exclude_from_pca)) {
    env <- c(env, spat_variables[[exclude_from_pca]])
  }
  names(d_exp) <- paste0("PC", 1:ind_exp)

  if(project){
    #Save current variables
    dir.create(file.path(out_dir, "/Current"), recursive = TRUE,
               showWarnings = FALSE)
    terra::writeRaster(env, file.path(out_dir, "/Current/Variables.tif"),
                       overwrite = overwrite)

    #Check scenarios to predict
    res_path <- check_pred_scenarios(projection_data = projection_data,
                                     out_dir = out_dir)
    #Show progress bar?
    if (progress_bar) {
      pb <- utils::txtProgressBar(0, nrow(res_path), style = 3)
      progress <- function(n) utils::setTxtProgressBar(pb, n) }

    for (x in 1:nrow(res_path)) {
      # Import scenario x
      sc_x <- terra::rast(list.files(res_path$input_path[x], full.names = T,
                                     pattern = projection_data$raster_pattern))


      #Predict
      p_x <- terra::predict(sc_x[[pca$vars_in]], pca)
      if(!is.null(exclude_from_pca)){
        p_x <- c(p_x, sc_x[[exclude_from_pca]])
      }

      #Write results
      dir.create(res_path$output_path[x], recursive = TRUE, showWarnings = FALSE)
      terra::writeRaster(p_x,
                         file.path(res_path$output_path[x], "Variables.tif"),
                         overwrite = overwrite)

      # Sets the progress bar to the current state
      if(progress_bar){
        utils::setTxtProgressBar(pb, x) }
    }

  } #End of project
  return(list(env = env, pca = pca, deviance_explained_cumsum = d_exp,
              projection_directory = out_dir))
}
